Updated follow-redirect package reference from http-proxy
SpringRoll/SpringRollStudio pull request #42
Opened 2022-01-18 21:04 UTC by TensAndTwenties

[Link to ticket](https://www.pivotaltracker.com/story/show/180949473)

2022-01-19 15:30 UTC, 902seanryan requested changes

2022-01-19 15:30 UTC, 902seanryan commented on CHANGELOG.md
> +## [1.1.0] - 2022-01-18
I'd just change this to 1.1.1 unreleased instead of adding on to 1.1.0

2022-01-19 20:42 UTC, deycorinne requested changes
just re-request my review once you address Sean's comment

2022-01-20 15:26 UTC, 902seanryan approved these changes

2022-01-20 17:40 UTC, deycorinne approved these changes

2022-01-21 14:25 UTC, merged