Added event listener to paste as plain text
SpringRoll/SpringRollStudio pull request #48
Opened 2022-01-27 15:27 UTC by lukemelong

2022-01-27 17:46 UTC, deycorinne approved these changes

2022-01-27 17:55 UTC, 902seanryan requested changes

2022-01-27 17:55 UTC, 902seanryan commented on src/renderer/components/caption-studio/TextEditor.vue
> +    document.getElementById('quill-editor').addEventListener('paste', catchPasteEvent);
can you use the `$ref` here instead of the get `elementById`? Its the more vue-ish way to do it

2022-02-01 18:05 UTC, 902seanryan approved these changes

2022-02-02 15:20 UTC, merged